version: 2

sources:
  - name: public_transit
    tables:

      - name: station_passenger_stats
        description: "Raw passenger counts at stations."
        columns:
          - name: station_id
            tests: [not_null]
          - name: clock_tick
          - name: total_passengers_in_station
          - name: passengers_boarded_trains
          - name: passengers_entered_station
          - name: passengers_waiting

      - name: train_location
        description: "Location data of all trains in system."
        columns:
          - name: clock_tick
          - name: train_id
          - name: segment_id
          - name: station_id
          - name: platform_id
          - name: train_queuing_order
          - name: train_position


          - name: total_passengers_in_station
          - name: passengers_boarded_trains
          - name: passengers_entered_station
          - name: passengers_waiting