version: 2

sources:
  - name: public_transit
    schema: "{{ env_var('DBT_SOURCE_SCHEMA', 'public_transit') }}"
    tables:

      - name: station_passenger_stats
        description: "Raw passenger counts at stations."
        columns:
          - name: station_id
            tests: [not_null]
          - name: clock_tick
          - name: total_passengers_in_station
          - name: passengers_boarded_trains
          - name: passengers_entered_station
          - name: passengers_waiting

      - name: runtime_passenger_state
        description: "Append-only log of passenger travel events."


      - name: runtime_rail_segment_state
        description: "Append-only log of rail segment activity."
        columns:
          - name: segment_id
          - name: clock_tick
          - name: trains_present
            description: "A JSONB array containing all trains currently on this segment."

      - name: runtime_world_clock_state
        description: "Append-only log of world clock state."

      - name: runtime_train_state
        description: "Append-only log of live train movements and statuses."

      - name: runtime_platform_state
        description: "Append-only log of platform statuses and docked trains."
